### PR TITLE
Implementing Setup Wizard and other changes

### PR DESCRIPTION
**Pull request by Liongold**
This pull request is quite a big one and contains 3 changes or features. Firstly, it fixes some of the options in the registration dropdown list being in code form by adding an entry in the language file. The second change is that of putting the registration in a partial file. This is done to help the Setup Wizard development. Then, the whole setup wizard has been implemented. I know it isn't perfect and is a little bit rough at the edges but it works and I think it is a good concept that can be improved with more testing and feedback. I'll take care of editing any relevant wiki pages to allow anyone to skip the wizard by setting relevant files in their place. For now, only MySQL connections can be set up through the wizard. Others will be implemented soon. 

Please note that the wizard adds sqlite as a need for Paperwork unless the user wants to skip the wizard, as shown in the warning page. After setup, sqlite can be removed and should not be needed anymore.

### CODE REVIEW

**Comment by Liongold** [comment]
This is the main part of the fix for #234.

**Comment by Liongold** [comment]
Update: sqlite is not needed anymore.

**Comment by Baldrs** [comment]
Does it work without composer install?

**Comment by Liongold** [comment]
@Baldrs: Until now, no. Currently, this kicks in after composer install, npm install, bower install and gulp are run. This does not mean that it has to remain like this however and can be further refined later.

**Comment by Baldrs** [comment]
Same thing as `php artisan paperwork:install` then. We need to make bundles prebuilt and persuade users to use them.

**Pull request merged**
