### PR TITLE
Added progress bar for requests

### LINKED ISSUE #288: Waiting cursor
Need to set waiting cursor (hourglass) and blocking page actions on long-time operations (create notebooks/notes, save changes, etc)

### PR DESCRIPTION
**Pull request by Liongold**
This is meant to close #288. It is using an external library. If the need arises, something else can be written specifically for Paperwork but I think this serves well the purpose.

### CODE REVIEW

**Comment by Liongold** [comment]
@Baldrs Are there any problem with this pull request?

**Comment by Baldrs** [comment]
Nothing special. Just next time please work with the latest develop.

**Comment by Liongold** [comment]
I did work with the latest develop. But this pull request has been open for a number of days and a lot of other requests were merged in the meantime. Anyway, if there's anything I can do, tell me.

**Comment by Baldrs** [comment]
We need add combination of all raw css into one because we have too much requests already.

**Comment by Liongold** [comment]
BTW, you're right. I thought I had created a new branch for this work but it seems that I only opened the pull request. Sorry for that. It was a mistake on my part.

**Comment by Baldrs** [comment]
Please fix that was reported in gitter ASAP, something went wrong with your
pull request

**Pull request merged**
