### PR TITLE
Fixing issue #382 => adding header to the Attachments' raw response.

### PR DESCRIPTION
**Pull request by clemlaf**
I went a step further in the workaround using the php header function. I still don't know why the $header array is not passed though.

### CODE REVIEW

**Comment by Baldrs** [comment]
Well official documentation for Laravel 4.2 states that you must set headers through `header` method of the response object. Can you please remove the third argument and convert your 'raw' header calls into method calls on the response object? See views & responses at laravel documentation

**Comment by Baldrs** [comment]
Also let file to be cached, don't decrease the performance, it is already poor

**Comment by clemlaf** [comment]
When I use the Response class's header method, the same problem occurs as the situation with the `$headers` array passed as argument of the `Response::make` call. The headers are not taken into account in the Response.
Actually I'm not sure that a Response object is really needed. If I set the headers using the php `header` function and I make `raw` return only the content of the file, it seems to do the job. Would that solution be inappropriate ?

As for the value of the Cache-control header, I did not intentionnally change it, I just took the value that was set in the `$headers` array, assuming it should be correct. Could you tell me what value should appear ?

**Comment by Baldrs** [comment]
Hold on the horses, mister. If we won't do it _Laravel_ way, why the hell do we need Laravel at all? We must find a working correct way to solve it without crutches.

**Comment by clemlaf** [comment]
I figured out what was the problem. Actually the call to the php function `readfile` bypasses the Response object. In php documentation, it is written that `readfile` writes to the output buffer and returns and integer for the number of bytes read. It means that the Response object's content was only the size of the file (and not the content). The content was actually sent to the client, with the wrong headers, before the Response object was constructed (and returned) with the right headers.

I changed the call to `readfile` to `get_file_contents` which returns a string that is passed to the `Response` object. That way the `$headers` array's content is taken into account. 

As for the Cache-control I set it to 'private' but I'm not sure it's correct.

**Pull request merged**
