### PR TITLE
Issue 349

### PR DESCRIPTION
**Pull request by Baldrs**
This resolves issue when paperwork is installed in subfolder. Https is working right too.

### CODE REVIEW

**Comment by Liongold** [comment]
What is this supposed to fix?What is the functionality that has been added?

**Comment by Baldrs** [comment]
Enables https://domain/paperwork/ installs to work

**Comment by Liongold** [comment]
I didn't know we could merge our own requests now.

**Comment by Baldrs** [comment]
Needed my both PRs on the server ASAP

**Comment by Liongold** [comment]
Did you test this? It does not work on my install.

**Comment by Liongold** [comment]
Does the URL have to be https or even http should work?

**Comment by Baldrs** [comment]
Yes, I have tested it using nginx setup. https is enabled and subfolder is
/paperwork/ (points to frontend/public). Did you rebuild the assets? Can
you tell exactly what is not working?

**Comment by Baldrs** [comment]
Http or https does not matter.

**Comment by Liongold** [comment]
Please specify that it works on Nginx only then. With Apache, without the .htaccess file I posted in the wiki, does not work. No change from previous behaviour.

**Comment by Baldrs** [comment]
Indeed it does not work without proper config on any web server. I'll write
an article on to how to do this on nginx and apache when I will come back
from vacation this monday

**Pull request merged**
