### PR TITLE
Implementing #14 (feature)

### PR DESCRIPTION
**Pull request by Liongold**
Added drag-and-drop feature to move notebooks. Includes switching to new notebook after move and some CSS feature. However, there's still a problem with the CSS but is not a blocker. 

If possible, please try to not merge the conflict fixing commit since it might not be good to be shown in the repo commit log.

### CODE REVIEW

**Comment by devilx** [comment]
Looks good. One thing: Could you please remove *all* console.log? [Some browsers](http://stackoverflow.com/questions/690251/what-happened-to-console-log-in-ie8) don't support that.

**Comment by Liongold** [comment]
I've removed the console.log(). Anything else?

**Comment by Liongold** [comment]
Sorry, I forgot the other function. I'll fix it as soon as possible.

On Sunday, February 15, 2015, Marius <notifications@github.com> wrote:

> Looks good. One thing: Could you please remove *all* console.log? Some
> browsers
> <http://stackoverflow.com/questions/690251/what-happened-to-console-log-in-ie8>
> don't support that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twostairs/paperwork/pull/239#issuecomment-74413037>.
>


-- 
Sincerely,
Jean Spiteri.

**Comment by Liongold** [comment]
I've updated the code so it should be good for merging.

**Comment by Liongold** [comment]
I've opened a pull request for issue #16 that includes the changes for issue #14. I think this pull request can be closed without merging then and the merge is done in #248.

**Pull request merged**
