### PR TITLE
Close collection when clicking title (one it is open)

### PR DESCRIPTION
**Pull request by Liongold**

### CODE REVIEW

**Comment by Liongold** [comment]
@JamborJan Can you check these requests please?

**Comment by JamborJan** [comment]
Hey @Liongold I'll check during the next days, hope it is not urgent.

**Comment by mrusme** [comment]
Shall this be merged? :)

**Comment by Liongold** [comment]
@mrusme Thanks for merging the previous pull requests. If you have time to merge this yourself, please do.

**Comment by JamborJan** [comment]
Hey @Liongold, I was now able to make a build with the new features but unfortunately I have not included collections in my Sandstorm build so far as this was a very weak feature until now. I will update my build to include it. Am I right that I need to check out your Paperwork fork with this branch to be able to fully test the feature?

**Comment by Liongold** [comment]
@JamborJan Yes, this branch includes the latest Collections code. Otherwise, you or @mrusme can merge this and then you can build the latest develop code to have the latest code.

**Comment by Liongold** [comment]
@JamborJan If you generate your build using the latest develop code, you should now have the latest code. 

@mrusme Thanks for merging these pull requests.

**Comment by JamborJan** [comment]
hey @liongold, unfortunately I'm completely absorbed by business projects, thats why I'm not responding so much lately. I'll test as soon as I have some time for it. If anybody is curious and wants to test on his own: the instructions in my repo should give you a up and running system within minutes: https://github.com/JamborJan/paperwork

To change to the develop branche you should change [these lines](https://github.com/JamborJan/paperwork/blob/master/.sandstorm/setup.sh#L65-L71) after the `git clone` step and before the `vagrant-spk vm up` step and make them look like this:

```
# Clone git repository for master build
#git clone https://github.com/twostairs/paperwork

# Clone other repos & checkout branches for tests
git clone https://github.com/twostairs/paperwork
cd /opt/app/paperwork/
git checkout develop
```

**Comment by Liongold** [comment]
@JamborJan Sorry if I sounded wrong. I was not at all asking you to do it, I was just updating my answer to your earlier question.

**Pull request merged**
