### PR TITLE
Trying implement evernote import.

### PR DESCRIPTION
**Pull request by 7brend7**
Trying implement evernote import.
Works for my 'enex' file exported by "evernote for windows"; but we need more testing.
The history and notebooks import haven't implemented; all notes are pushed to the 'Evernote' notebook, but tags and attachments are supported.
Also I noticed that for correct html display we need to add angular filter for output raw html (http://stackoverflow.com/a/25500347).

### CODE REVIEW

**Comment by Baldrs** [comment]
No need in custom filters - there are ngSanitize and ng-bind-html directive for that.

**Comment by Baldrs** [comment]
I'm gonna apply some refactoring to this, please don't merge

**Comment by Baldrs** [comment]
Well checked that with my own ~12 clipped notes, does not work at all(only one note gets imported), attachments don't work(seems to be other bug), will try to improve the code to get it work.

**Comment by Liongold** [comment]
This could be merged to a temporary branch, be checked in a more full way and then merged to develop. What do you all think?

**Comment by Baldrs** [comment]
I managed to get it work, it although needs some improvement. Also I
discovered severe performance degradation on 'large'( >20) note sets, that
needs fixing.

**Comment by Baldrs** [comment]
Also we need to change the way the attachments are served - and better let webserver to serve files(for example nginx does this very good)

**Comment by jamesrascal** [comment]
I second the Attachment saving as there is an issue with it see #395

**Pull request merged**
