### PR TITLE
Issue 132 feature: Add calendar multiple filters and toggling of filters.

### LINKED ISSUE #132: Feature request: calendar
It would be nice to have calendar feature to make easier to switch between years.
For example, its good for personal journal.

### PR DESCRIPTION
**Pull request by ChrisLahaye**
- Use of multiple filters (example: searching for notes with a specific tag in notebook on date)
- Toggling filters on and off
- Filters are displayed in the search input field for user feed-back
- Calendar is being displayed in sidebar, only dates of the current displayed notes are visible.

Fixes #132, thoughts?

Technical demo at IP 188.226.188.65 with virtual hostname "paperwork.plato".
To visit append the hosts file with the following line:
```
188.226.188.65	paperwork.plato
```
Then visit paperwork.plato
calendar

### CODE REVIEW

**Comment by Baldrs** [comment]
Can you please update the calendar style so it won't look alien to the whole theme?

**Comment by Baldrs** [comment]
4093bb18-b7c9-11e4-945e-9d82fa940c41

**Comment by Baldrs** [comment]
BTW, have you added locale settings support or something like?

**Comment by devilx** [comment]
What's the status here? @ChrisLahaye @Baldrs

**Comment by Baldrs** [comment]
I think style needs more adaptation to paperwork style

**Comment by ChrisLahaye** [comment]
@Baldrs: I know it's not yet finished but its a developer branch. I decided to push it so other people can test the functionality and assist me by making their own changes.

Running up against some small problems.
1. Bootstrap-Datepicker library uses Glyphicon icons which are currently not embedded in Paperwork's Bootstrap build. Whats the preferable solution, modifying/patching the library to use other classes, adding the classes/icons manually or a dirty modification at run-time via JavaScript.
2. The "alien" colors appear because of the default Bootstrap style caused by the pseudo-classes at the .btn-info class, which is the class used by the library for every button representing a day. Ofcourse I can overwrite the style in the .tree-calendar class but we must look for a project-wide solution. I've never used less before so if somebody could help me with that.
3. In the SidebarNotebooksController (see commit bd81784) the $watchCollection method fired the event 7 times for some reason. It shouldn't fire multiple times because the $rootScope.notes is only loaded once after loading the note list?

**Comment by devilx** [comment]
@ChrisLahaye just resolved the conflicts and merged it. Please test the current develop version to make sure I didn't screw any of your code up.

Regarding the glyphicon stuff: We use FontAwesome instead. So basically the best thing would be to include the Bootstrap-Datepicker CSS stuff into our paperwork-v1 theme (maybe as a separate less file) and try to make the classes use FontAwesome instead of Glyphicon. Regarding the LESS: You can basically copy & paste the CSS into the LESS file and import that one within paperwork-v1.less – no further LESS knowledge needed. We should keep this part pure CSS, so when the bootstrap-datepicker change their CSS, we can easily adapt to these changes.

Regarding the firing: Right now, on every selection of a new notebook the notes list is being loaded (no caching atm). Maybe that's the reason?

**Comment by ChrisLahaye** [comment]
@devilx I just tested the develop branch and everything is working.

I agree that we should make use of the fa classes instead of glyphicon, but how? What's the best way of doing this, changing the classes at run-time via JavaScript or modify the existing library? If we decide to modify the existing library its best to not do this directly but via patching for in case if later the decision is made to use a package manager (like bower) instead if static files.

Regarding the LESS, I managed to get that far. I believe we should not modify btn-info's style in a very specific selector (<sub><sup>.tree ul.tree-child li.tree-calendar .btn-info:hover, .tree ul.tree-child li.tree-calendar .btn-info.active</sup></sub>) but with a more generic one that matches the whole project (like .btn-primary). Though I've no idea where to do this because I am unfamiliar with the current/LESS structure.

Regarding the firing, there is definitely something wrong with it. Look at the screenshot, the same request is to notebook or tags for example is made multiple times, even the response is the same.
Network usage Paperwork

**Comment by devilx** [comment]
Here's some pseudo LESS, that might actually work for your case:

paperwork-v1/paperwork-v1-bootstrap-datepicker.less
```
@import "../../font-fontawesome/variables.less"

.glyph-globe {
  .@{fa-css-prefix}-globe;
}
```

Using such a LESS structure would mean, that, when the library uses the class ```glyph-globe``` somewhere, it would be overwritten by our theme and include the font-awesome icon, instead of the glyph one. I haven't tested this yet, but theoretically it should work. The only need needed to be done would be to create such a LESS file, that redefines all classes.

Regarding the multiple loading: We need to investigate this.

**Comment by ChrisLahaye** [comment]
@devilx Thats genius :D Will test tomorrow!

**Pull request merged**
