### PR TITLE
Updated CKEditor to 4.6.1

### LINKED ISSUE #723: Update CKeditor. it is 2 years old!
After trying for hours to update CKeditor I finally found the issue why it wouldn't work.

frontend/app/js/paperwork/sidebar/notes.controller.js > Line 177
`CKEDITOR.instances.content.destroy()`

This breaks angular due to CKeditor flags.
I commented it out and CK works great now. Full HTML editing capability.

@Liongold please update it... use my fork if you wish.

Also, FontAwesome is no longer supported so I added it manually.

### PR DESCRIPTION
**Pull request by Liongold**
Fixes #723. May also improve the auto-save situation, as described in #725. 

Fontawesome support is missing. 

@mrusme Does this make the pull request unmergeable?

### CODE REVIEW

**Comment by Liongold** [comment]
Thanks to the new commit added, this also replaces #730.

**Comment by Liongold** [comment]
Closing and reopening request to generate builds

**Comment by kevthehermit** [comment]
Do you know when this will get merged, wanting to update my production instance, but its docker so need to wait for this

**Comment by Liongold** [comment]
@mrusme Do you have any time to check this out please?

**Comment by mrusme** [comment]
@Liongold I'm not 100% sure about this. Have you tested it locally?

**Comment by Liongold** [comment]
@mrusme Yes, I've tested it. If you are uncertain about anything, no problem, I can test it in a better way. However, if it isn't a problem for you, could you take care of the other requests? They should be small updates but are pending for quite some time.

**Comment by Liongold** [comment]
As I've said, the Font Awesome plugin is missing because there does not seem to be a plugin for this version.

**Comment by kevthehermit** [comment]
@Liongold @mrusme any movement on this, Or shall i just create my own fork for now.

**Comment by Liongold** [comment]
@kevthehermit I don't have any more information to share on this.

**Comment by mrusme** [comment]
@kevthehermit feel free to fork -> implement -> PR. :-) 👍

**Comment by Liongold** [comment]
Thanks @mrusme for taking a look at all the pending requests.

**Comment by mrusme** [comment]
@Liongold sure thing, sorry for the delay

**Pull request merged**
