### PR TITLE
Check for commit timestamps and branches during update check

### LINKED ISSUE #330: Error text
When the latest commit in the local copy is not equal to the one in paperwork GitHub repo, this message appears in error-reporting box "Found a bug? It seems like you are not running the latest version of Paperwork. Please consider updating before submitting an issue."

But sometimes it is because people committed to their repo that the latest commits in the two repos are different, this message may be misleading.

### PR DESCRIPTION
**Pull request by Liongold**
This pull request is meant to fix #330. It also triggers the error_version_check text when the user is in a branch named differently from any other branch in the Paperwork Github repository.

### CODE REVIEW

**Comment by Liongold** [comment]
Pull request suspended

**Comment by Liongold** [comment]
Pull request reopened. No problem with the code.

**Comment by Baldrs** [comment]
Don't use array() notation, we don't support PHP less than 5.4.

**Comment by Liongold** [comment]
Why is the Travis build failing while it's working normally?

**Comment by Baldrs** [comment]
@Liongold because you've broken something in git update check, it has some rudimentary unit tests

**Comment by Liongold** [comment]
@Baldrs The builds are passing now. However, one build is still failing. This is the pr 5.6 build. However, it seems like npm install is failing with an error similar to cb() never called so I'm not sure if it has to do with the commits themselves or something else.

**Pull request merged**
