### PR TITLE
UI Enhancements

### PR DESCRIPTION
**Pull request by wongalvis**
### Screenshots for the new setup UI
screencapture-upkkeb526fb2-pwmvx128-koding-io-login-1455694586029
screencapture-upkkeb526fb2-pwmvx128-koding-io-login-1455694591071
screencapture-upkkeb526fb2-pwmvx128-koding-io-login-1455694598008
screencapture-upkkeb526fb2-pwmvx128-koding-io-login-1455694602223
screencapture-upkkeb526fb2-pwmvx128-koding-io-login-1455694606193
screencapture-upkkeb526fb2-pwmvx128-koding-io-login-1455694610420

### Known issues
- db_settings cannot be written properly (and 500 Internal server error is returned) note: folder was set to permission 777
- File 'setup' is not always removed after setup

### CODE REVIEW

**Comment by mrusme** [comment]
@wongalvis sorry for the *huge* delay. I think these changes are in conflict with a few things @Liongold changed in his PRs.

**Comment by wongalvis** [comment]
It's quite a large conflict, I guess I'll work on it again some day.

**Comment by Liongold** [comment]
@wongalvis I'm sorry for breaking your work. I really hope you rework on this and other parts of Paperwork. If you need any help, please tell me.

**Comment by wongalvis** [comment]
@Liongold It's ok, you've done adjustments on the backend so I agree too that it is better to have your work merged. I'll see to reworking as well as working on other parts. :)

**Pull request closed without merging**
