### PR TITLE
Implementing Export Function in ENEX format

### PR DESCRIPTION
**Pull request by Liongold**
Please do not merge this for now. 

This is the first version of the export function. It exports all notes in an ENEX file. Could you please check it out?

I've added some strings in the en language. However, they are not added in de.

### CODE REVIEW

**Comment by devilx** [comment]
It looks good from what I see within the diffs. The next step would be to check, if there was a way to use the internal Blade-Templating-Engine to generate the output file, so that you don't need to mix the "view" (XML structure of the export file) with the controller code. But that's only some cleaning that could be done at a some point in the future.

However, just tell me whether you're done with this and you want me to merge it, or if you'd still like to implement something.

Thanks again for your work! :+1:

**Comment by Liongold** [comment]
I'm trying to do the separation, as you've commented. It isn't ready for now yet. My pull request also includes a couple of strings. Will those be translated before merging or can be done after?

**Comment by devilx** [comment]
@Liongold the translation can be done later, since you probably don't know german or french, right? :-) Don't worry about that.

**Comment by Liongold** [comment]
I've updated the request while adding the remaining strings. Please check it and if it's good, you can merge it ;)

**Comment by devilx** [comment]
Looks good! Great work, thank you!

**Pull request merged**
