### PR TITLE
Various fixes in notes_edit.controller.js and api Notebook php controller

### PR DESCRIPTION
**Pull request by clemlaf**
When reading the js code of notes_edit.controller.js, I found out that there were no quotation marks around a regular expression, so I corrected it.
Also, I had an Exception when I tried to delete a notebook, and the reason was that the mysql query looked for an 'uuid' field in a table where the field was named 'id'. I corrected that too.

### CODE REVIEW

**Comment by Baldrs** [comment]
Quotation marks are not needed in js as there regex literal /regex/, so in quotes it won't work unless it is passed to a RegEx constructor

**Comment by Baldrs** [comment]
I reviewed the PR(again), and what I got to say, is that it has to use UUID as @devilx introduced them in #66, so it may be related to an obsolete database, BTW.

In general, if it is not working with the latest database from develop(fresh install), it is got to be fixed in the database.

**Comment by clemlaf** [comment]
Then how come this code in the api controllers works ?
`$join->on('notes.notebook_id', '=', 'notebooks.id');`

**Comment by clemlaf** [comment]
The bug was found when I wanted to delete the welcome Notebook just after setting a new database, so it is not related to an obsolete database. Besides, the «initialize.php» file in the /frontend/database/migration folder contains the following 
`        Schema::create('notebooks', function(Blueprint $table) {
            $table->char('id', 36)->default(NULL)->primary();
`
So it seems that for the database, there is not 'uuid' field in notebooks table, but an 'id' field.

**Comment by Baldrs** [comment]
Well, if it is not, it has to be `uuid`, specifically `$table->char('uuid', 36)`

**Comment by clemlaf** [comment]
It is odd, because, before my commit, a `git grep uuid` returns only commented lines, except in the notebook destroy function. It also happens that this function did not work, and the exception raised was related to an unexisting uuid field. That is why I corrected that (it is only the name of the field, not the content). If I understand your comments, the correction should be the other way around, so that all controllers are changed in order to replace notebooks.id by notebooks.uuid. What about notes ? and users ?, they all use an id named field.

**Comment by Baldrs** [comment]
That's needs to be fixed to use uuids

**Comment by Baldrs** [comment]
I see now, inside migrations lies the answer, all the columns are actually named `id` and they contain `uuids`.

**Pull request merged**
