### PR TITLE
Added bootstrap-editable.min.js file to resolve 404 error

### PR DESCRIPTION
**Pull request by Liongold**
This fixes issue #516 as a result.

### CODE REVIEW

**Comment by Baldrs** [comment]
Jean, please remove the stuff from js folder and do it via gulp and bower

**Comment by Baldrs** [comment]
It was removed by purpose and there is no need to put it there again

**Comment by Liongold** [comment]
OK, will do.

**Comment by Liongold** [comment]
The pull request is now fixed.

**Comment by DavidJacobson** [comment]
When will this pull be merged with the master branch?

**Comment by Liongold** [comment]
@DavidJacobson The master branch will be updated with the develop branch code soon, depending on the level of activity in the project. If you think this should be done earlier, please tell us however.

**Comment by Baldrs** [comment]
@DavidJacobson it is left to mege 2 commits to trigger 50 commits rule(that's until we will have any better).

**Pull request merged**
