### PR TITLE
Update notebooks.php

### PR DESCRIPTION
**Pull request by DavidJacobson**
Minor grammar change

### CODE REVIEW

**Comment by Liongold** [comment]
@DavidJacobson Sorry for the delay. Is it a problem for you if you do this change through Transifex? https://github.com/twostairs/paperwork/wiki/Translating.

**Comment by DavidJacobson** [comment]
No, not a problem, where is that located in the repo?

**Comment by Baldrs** [comment]
Transifex only, sorry guys.

**Comment by Liongold** [comment]
@DavidJacobson I don't have an account on this so I apologise if I don't respond 100% accurately. However, I think that you can join the project through this link: https://www.transifex.com/twostairs/paperwork/. @Baldrs can tell you if there's a need for approval.

**Comment by Baldrs** [comment]
@DavidJacobson already approved you on Hebrew language

**Pull request closed without merging**
