### PR TITLE
Minify JS files with gulp-uglify

### PR DESCRIPTION
**Pull request by cfj**
I don't know if you had any special reason for not minifying the JavaScript. Anyway, it's a small change and here it is if you want it. I added sourcemaps for the Paperwork files so you can still debug in the browser.

### CODE REVIEW

**Comment by devilx** [comment]
Thank you! Could you somehow make this configurable? The reason for not minifying JS was, that we need more speaking errors when something goes wrong.

**Comment by cfj** [comment]
How about a separate task, called 'prod' or something, that runs the default tasks then adds minification on top of that?

**Comment by devilx** [comment]
@cfj sounds good for me!

**Comment by cfj** [comment]
@devilx Cool. I've updated this PR.

**Pull request merged**
