### PR TITLE
Added line to help with some Out Of Memory errors that occur when imp…

### PR DESCRIPTION
**Pull request by codejockey1**
…orting large Evernote notebooks

### CODE REVIEW

**Comment by Liongold** [comment]
Sorry for not explaining myself well. I did not mean this change but the change I proposed in a comment to fix the actual issue not this change. Could you please test that and submit the pull request with that change please?

**Comment by codejockey1** [comment]
Done

**Comment by Liongold** [comment]
@codejockey1 I would avoid the ini_set call. If anyone encounters any issue, the memory limit could be increased in the php.ini file. What do you think?

**Comment by Liongold** [comment]
@codejockey1 Any progress?

**Pull request merged**
