### PR TITLE
Update this branch with latest develop changes

### PR DESCRIPTION
**Pull request by Liongold**

### CODE REVIEW

**Comment by Liongold** [comment]
I'll proceed in merging since this is a development branch.

**Comment by Baldrs** [comment]
How about to merge some other pull requests instead of self-merging branches?

**Comment by Liongold** [comment]
@Baldrs I needed to do this in order to be able to work on the Git feature. Sorry for not merging your branches but I don't use the Calendar feature so didn't know what to test.

**Comment by Liongold** [comment]
And to clarify this is not self-merging because this branch is totally unrelated to work on Paperwork and is just a branch for work on one particular type of feature in Paperwork. This was done to avoid conflicts later on.

**Pull request merged**
