### PR TITLE
Issue 132 feature: Filtering by date improved and fixed

### LINKED ISSUE #132: Feature request: calendar
It would be nice to have calendar feature to make easier to switch between years.
For example, its good for personal journal.

### LINKED ISSUE #260: Filtering by date (selecting a calendar day) disables filtering by other dates.
If you select a day in the calendar on the left menu, the other dates that were previously bold to show there are notes from those days become disabled.

### PR DESCRIPTION
**Pull request by ChrisLahaye**
Fixes #260
Fixes #132

- Add ApiCalendarController
- Add route for api/v1/calendar to ApiCalendarController
- Add getCalendar method to notebooks.service.js that executes the API
request
- Change filter for disabled calendar days in notebooks.controller.js
- Remove garbage assignment to $rootScope.tags

### CODE REVIEW

**Comment by Baldrs** [comment]
There is must be something that can fix these travis builds from accidentally fail to `npm install`

**Comment by devilx** [comment]
Wait what? What exactly do we need a new API endpoint for? @ChrisLahaye mind explaining me, why this couldn't have been done using the ```notes``` endpoint?

**Comment by ChrisLahaye** [comment]
Did it for future purposes for in cases we ever create a full page calendar or any synchronization protocols. Would be better then to use another controller instead of smashing everything in notes.

But tell me to change it and I will

**Comment by Baldrs** [comment]
I think we don't need to add new entities without a worthy reason

**Comment by joshlemer** [comment]
@devilx @baldrs is this PR closed until @chrislahaye does the changes baldrs mentioned?

**Comment by Baldrs** [comment]
@joshlemer I think yes, and he anyway needs to resolve other calendar problems

**Comment by ChrisLahaye** [comment]
Other calendar problems are fixed if you took the effort to test the changes or report issues. Will make my last changes for the same endpoint this weekend or next week.

**Comment by Baldrs** [comment]
@ChrisLahaye any updates on this? Have you changed it to use existing api?

**Comment by Baldrs** [comment]
Okay we will improve that later, if that thing fixes that annoing filter behavior it is not that evil.

**Pull request merged**
