### PR TITLE
issue #265 do not sanitize html store in database.

### PR DESCRIPTION
**Pull request by clemlaf**
sanitize loses some format. implemented unsafe filter to leave html in database as is when showing a note

### CODE REVIEW

**Comment by Baldrs** [comment]
Can you provide an example when allowing XSS is the only solution?

**Comment by clemlaf** [comment]
I was thinking that maybe, since we only want to show Html that is stored in Paperwork DB, it is not the good time to sanitize html. The problem in #265 is that ngSanitize strips inline style attributes, and there is no way to add inline style attributes to ngSanitize white list. One way to keep this attribute is to trust the html.
I read somewhere that there is a custom ngSanitize version that allows inline style attributes. If you really think that paperwork cannot trust html that is stored in its own database, then this modification is not the right path to solve #265 and i'll look into the othe solution.

**Comment by Baldrs** [comment]
@clemlaf we're going to introduce web clipper extension later, so yes, we can't trust html. One key features that we struggle to provide is security and privacy, so even a possibility of XSS is not an option. Can you please find a solution that just allows style tags?

**Comment by clemlaf** [comment]
[textAngular](https://github.com/fraywing/textAngular)'s version of ngSanitize allows inline style and fills our need (does the same job as angular-sanitize but does not strip inline style). In order to use this script we could either:
 - add a bower dependency to textAngular and then only use textAngular-sanitize.js
 - fork textAngular-sanitize.js into a paperwork-sanitize.js 

The former seems easier to maintain.
The latter avoids unnecessary dependancies and lets customization available in the future.

My personal opinion : 1st solution (only 2 files to change)

We could also change from ckeditor to textAngular, but I'm not sure there is "insert math" and "insert fontawesome" plugins off the shelf.

**Comment by Baldrs** [comment]
Well textAngular seems interesting. We can move to it, I think, and retain CKEditor an option, because CKEditor does not play well with angular and causes problems. 

One more question, about their ngSanitize, do they filter malicious styles? Do they allow all css inside or  a safe subset?

**Comment by clemlaf** [comment]
textAngular's ngSanitize only allows the color, background-color, text-align, float, width and height attributes.

**Comment by Baldrs** [comment]
Good, then add it instead standard to solve this problem.

**Pull request closed without merging**
