### PR TITLE
Translated the new parts

### PR DESCRIPTION
**Pull request by Haroenv**
I am however not really sure about validation.php. In Dutch the order of that sentence is different, so I'm not sure whether $name_error_message is correct

### CODE REVIEW

**Comment by Haroenv** [comment]
I might have change some spaces to tabs too

**Comment by Baldrs** [comment]
Just of curiosity, did you use transifex for this?

**Comment by Haroenv** [comment]
No, Dutch is my native tongue

**Comment by Baldrs** [comment]
Two important things, https://www.transifex.com/ is a service that we use to translate paperwork without need to edit sources directly.

Second important thing is that all new functionality/translations must be merged into develop, not in master branch. Can you please change your PR from master to develop branch?

**Comment by Haroenv** [comment]
Okay, I'll do that tomorrow then.

**Comment by Haroenv** [comment]
Thanks, I didn't feel like getting to know transiflex just for this

Haroen

**Comment by Baldrs** [comment]
Next time please use transifex

**Pull request merged**
