### PR TITLE
Adding status notifications

### LINKED ISSUE #146: Missing notifications on deleting a Notebook / Note
There is no notification after deleting a notebook or note. It would be nice to show a notification "The notebook have been deleted successfully"  or something similar after deletion.

### PR DESCRIPTION
**Pull request by Liongold**
In this pull request, I have added a new service that can be injected in other modules to show notifications about the success or failure of an action. I have added it to a number of actions. If anyone encounters any issues, I'll be more then happy to give a look to them. This pull request includes a new language file. I don't know if I can trigger a refresh of transifex. If I can, please let me know how. In order to avoid users seeing blank notifications, I'll copy the English file to all other languages. This fixes #146.

### CODE REVIEW

**Comment by Baldrs** [comment]
First of all, some notes.

1. Learn dom basics. You doing it wrong.
2. Learn how CSS works. You doing it wrong.
3. Learn javascript. You doing it wrong.
4. Learn jQuery, you doing it wrong.
5. Learn Angular, you doing it very-very wrong.

**Comment by Baldrs** [comment]
PS: When you have new translation, contact either me or @devilx to add it to transifex. We then will pull the translations  in.

**Comment by Liongold** [comment]
I know it's late but I'd like to post some comments. First of all, I'd like to point out that I'm still in the process of learning (not that it ends anyway) so I might not know everything or even a lot. With that said, I'd like to point out that I have no idea about what's wrong with the DOM and CSS. Funnily enough, I don't see that you've touched anything except that needed to change the whole thing into a directive. I don't see anything wrong with Javascript because it got removed completely and was replaced by jQuery. I'm not very knowledgeable in jQuery, I admit, but I don't see anything so wrong in this, except the missing $ in front of variable names. 

Also, I'd like to point out that in other communications, you asked others to write good commit messages. No problem with that but wanted to make sure that you practice it yourself since you have two commits with the same message. How good is that? I don't know because I'm not a Git expert. A little pointer on the ridiculous code parts would be a good thing to do anyway. 

Just my uninformed opinion from a person still from a person in initial learning stages.

**Comment by Baldrs** [comment]
Yes, I did not change anything except removing margin adding in favor of high z-index, and did it angular-way. Anything else (ie idea) remained as you authored.

Why it is better that way - it removes the necessity to know the structure of the html from controllers. Your original solution required service to know about how the layout is constructed, ie tied service to the html, which is wrong, because service must have [single responsibility](https://en.wikipedia.org/wiki/Single_responsibility_principle). 

In angular, directives encapsulate work with html, so you don't need to tie it to some layout or know how does it work - you just drop it in where it belongs. 

So using the proper way gives you possibility to replace notification service and its representation with some other components, without changing the rest of application. This in future will give better maintainability. 

About $ in jQuery variables it is simply a naming convention in jQuery code that means that this variable is a jQuery object, which gives you easier-to-read code with distinguishable variables.

Regarding same-message commits, you may know I'm a human being like you and I make mistakes too. So I have pushed that commit before I realized that I forgot to commit one more thing, thus this may be considered the same commit.

I apologize if you took any offence from my comments, I've just wanted to point you the importance of doing things right from the very beginning.

PS always remember jQuery != javascript.

**Comment by Baldrs** [comment]
PPS Asking if you don't know or don't feel how it is done rightly, don't hesitate to ask us about.

**Comment by Liongold** [comment]
Yeah I accept everyone makes mistake. In no means, I wanted to imply that you lacked knowledge or anything like that.

**Pull request merged**
