### PR TITLE
Better docker-compose packaging/building

### LINKED ISSUE #696: Docker variables for database are not set
With the current docker-compose script, the database migrations within the `docker-runner.sh` cannot run since the database configuration hasn't been established yet. I was planning on submitting a pull that fixes this. I attempted to write out the configuration based on the environment injected from the linked database container: 

```
cat << EOF > /app/app/storage/config/database.json
{"driver":"mysql",
 "database":"$DB_ENV_MYSQL_DATABASE",
 "host":"$DB_PORT_3306_TCP_ADDR",
 "username":"$DB_ENV_MYSQL_USER",
 "password":"$DB_ENV_MYSQL_PASSWORD",
 "port":"$DB_PORT_3306_TCP_PORT"
}
EOF

# Ensure migration is performed and database is not empty.
if [[ ! -e migrated ]]; then
    php artisan migrate

    touch migrated
fi

/run.sh
```

After this, when I start paperwork, I get to the 2nd screen "Customize your Paperwork" but when I attempt to move past it, I get the following:

```
Configuration has not been set correctly. Please try again. 
```

I've been trying to understand the setup code but am a bit lost with the controller structure. What other configuration file(s) do I need to write in order to automate the DB creation process with docker compose?

### PR DESCRIPTION
**Pull request by sumdog**
Fixes #696

This merge requests does a couple of things:

    Removes the exposed MySQL port and instead, uses container linking variables
    Handles configuration using docker env variables (setup in docker-runner.sh)
    Waits to ensure mysql is up before running migrations

### CODE REVIEW

**Comment by Liongold** [comment]
Why is the Setup Wizard being skipped in this pull request?

**Comment by sumdog** [comment]
At least the first page in setup should be skipped since we're setting up the database in docker, with linking and docker-compose. The docker wrapper also preforms the migration. (Or is there a way to show the database setup page with existing settings populated?)

I'd rather leave out the paperwork.json and have the wizard pick up there, but any attempts I made (various numbers in the setup file) always gives me errors as documented in #696 

With this patch, everything done in the setup wizard is controlled by docker environment variables. With this branch, you can `docker-compose up`, register and then restart the paperwork container with registration disabled if you wish.

**Comment by Liongold** [comment]
Is it possible to remove database setting up from the docker compose then? Also, is there to make sure all dependencies are installed?

**Comment by sumdog** [comment]
Well that's the way it was before, which defeats the entire point of using docker-compose and linking a mysql container. In fact in the current master, you expose the mysql port (big no-no; refused to start because it conflicted with my local mysql) where as with this patch, it uses the docker link environment variables and only exposes the mysql connection between the two containers. 

In the docker/docker-compose world, you shouldn't need a wizard or configuration. Everything should be configured using the environment variables. Give it a shot. Checkout my branch and do a `docker-compose up`. You'll immediately get to a fully running and configured paperwork on the first try. Changing the configuration is as easy as changing the docker-compose file.

**Comment by Liongold** [comment]
Sorry for that comment then. You're right, it's docker's job to skip configuration. However, is there a check for all needed dependencies?

**Comment by sumdog** [comment]
No worries. I haven't touched the `frontend/Dockerfile`. There are some optional dependencies missing (I get warning messages that the PHP-curl extension is missing). I was going to put that into a separate pull request. I'll be doing some more docker testing as I get free time this week; going to deploy it to my hosting provider.

I'll also update the `docker-compose` wiki page when this gets merged in to mention all the env variables and how to use them.

**Comment by Liongold** [comment]
Thanks for your contribution and sorry for taking so long to merge.

**Pull request merged**
