### PR TITLE
Add reference to irc channel

### PR DESCRIPTION
**Pull request by Baldrs**
It is not obvious that it even exists, but in issues people point to it( #148 ).

### CODE REVIEW

**Comment by Liongold** [comment]
Thanks for this.

**Comment by Liongold** [comment]
I can't merge right now. Sorry someone will have to do it or I will do it later.

**Comment by Baldrs** [comment]
Build failure seems to be unrelated to that PR, it is npm failing because of permissions somewhere

**Comment by Liongold** [comment]
I know.

**Comment by Liongold** [comment]
I know.

**Pull request merged**
