### PR TITLE
Basic Git Update Check

### PR DESCRIPTION
**Pull request by Liongold**
As discussed with @devilx, I'm adding some dirty code to check if the latest commit in the user's instance is identical to the latest commit in Github repo. This should reduce the number of bugs reported for already-fixed issues. This is only temporary and should be reduced by a much better fix when releases start to be done.

### CODE REVIEW

**Comment by Baldrs** [comment]
And what if guy does not have git installed? For example, downloaded packaged release? Or is at windows and has git.exe but not in path?

**Comment by Liongold** [comment]
@Baldrs This is temporary. I don't think I should waste so much more text to someone who isn't interested in reading pull request descriptions. 

I don't have testing access to Windows I don't know it works. However, if you have access to a Windows system, you could test it yourself and change where needed.

**Comment by Baldrs** [comment]
@Liongold people are too lazy to read PR descriptions. I read it, because I read them all if I want to merge, but in general, people won't read them. As they would not know why something is failing. For example, I'm quite sure most of the people don't have git on server. There are too much situations, and you even don't bother that git is installed.

**Comment by Liongold** [comment]
@Baldrs Fixed the 'check if git is installed' part. What is the problem with the requests in templates?

**Comment by Baldrs** [comment]
@Liongold maybe you forgot to push? I see rather unused exec in template, which runs `which git` but does not use that result at all.

The problems with templates are:

1. They will slow down the whole template generation or even fail if github is down/ddosed. 
2. It is useless if there is no git installed on the users server or user have deleted `.git` folder.
3. It is logic in templates, unnecessarily duplicated(you have three exact code fragments in three different template files, whereas you could just do this in some class on init once a day and then just use cached result in template)
3.1 It must be stored in a single class
3.2 It must be cached and updated infrequently.
4. As this is an update check it has to be fired only for admin users anyway, not for everybody.

I understand that we certainly need such a check, but in a some proper way involving minimum set of extraneous dependencies, like git. Like we could generate some file on build stage, which will hold sha1 and then use solely github api, disregarding os/git availability.

**Comment by Liongold** [comment]
Can you try it again? It works in my install.

**Comment by Liongold** [comment]
@Baldrs BTW, a user needs to have a .git folder if he wants to update Paperwork and contribute to it. Will see what I can do about the other parts. I don't agree with 4 because that would lose its effect (that of reducing issues for fixed problems).

**Comment by Baldrs** [comment]
@Liongold if an user is smart enough to contribute into code, he will be aware of some git workflow anyway

**Comment by Liongold** [comment]
@Baldrs Why wouldn't he get that he needs to update Paperwork?

**Comment by Liongold** [comment]
When we actually start doing builds, this will be removed so commen sense tells me that we can't create a file when we do not do builds.

**Comment by Baldrs** [comment]
We can start a practice of making nightly builds, and make them preferred way of installing paperwork.

**Comment by Liongold** [comment]
That suggestion doesn't have to do with this for now. I've already discussed this feature with @devilx, it's unfortunate that he is currently inactive. This is just a small thing that helps to identify latest version when submitting new issues and working on new features.

**Comment by Baldrs** [comment]
I'll add some stuff to make it out from templates, be cached and infrequent.

**Pull request merged**
