### PR TITLE
Check for when we have no selected users

### PR DESCRIPTION
**Pull request by Mezzle**
Fix Whoops in Admin when we click "Delete" or "Restore" when we've not selected a user.

### CODE REVIEW

**Comment by Liongold** [comment]
Thanks again. Could you point this to the develop branch please?

**Comment by Mezzle** [comment]
@Liongold could you please merge master into develop then?

**Comment by Liongold** [comment]
Paperwork contributing is detailed in a wiki page. To work on a feature or bugfix, please create a new branch from the develop branch, develop the feature/bugfix and then open a pull request to develop. The master branch is then periodically brought back in line with develop. If there any issues on master, which you think require that master is updated, please post. However, new contributions should be pointed to develop.

**Comment by Mezzle** [comment]
Can I suggest then that you make a CONTRIBUTING file to make this clear to people?

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Pull request closed without merging**
