### PR TITLE
Issue 467 bugfix

### PR DESCRIPTION
**Pull request by JamborJan**
Exports are now working.
Tested with smaller amounts of data and Evernote Mac 6.0.16 (451862)
Import in Paperwork still pretty unstable, see https://github.com/twostairs/paperwork/issues/13

### CODE REVIEW

**Comment by JamborJan** [comment]
This solves: https://github.com/twostairs/paperwork/issues/467

**Comment by Baldrs** [comment]
Nice, have you tried to import into latest DB structure?

**Comment by Baldrs** [comment]
Or it is your solution to the #462?

**Comment by JamborJan** [comment]
I try to use my time wisely with as much positive impact as possible for the project. So my goal is to solve #462 by making export / import work properly instead of wasting gime for a one time script.

Importing the data is still super weak also with new DB structure. I am looking at this now.

**Pull request merged**
