### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by Baldrs**
As the progress continues and we don't have stable version(yet) I propose to make another master branch update, as it is quite broken and we have many changes and fixes that will hopefully will resolve some of the issues(people are using master as well).

### CODE REVIEW

**Comment by Liongold** [comment]
I think that we should wait until @devilx comments on this before merging.

**Comment by Baldrs** [comment]
He's very busy last time, it may take a while until he sees that.

**Comment by Liongold** [comment]
Let's wait a week or a little more and then we'll see. What do you think?

**Comment by Baldrs** [comment]
Ok if we receive no input till next sunday, we merge this if we all agree on the point. Also I propose to merge every 50 commits till we have a stable release.

**Comment by Liongold** [comment]
@Baldrs OK, I agree. If anyone wants to put his feedback from the others, please do.

**Comment by Baldrs** [comment]
Bug label is just a mistake - my daughter jumped on my keyboard.

**Comment by Liongold** [comment]
No one objected to this so it can go ahead. Are you going to merge this yourself or not?

**Comment by Baldrs** [comment]
Yes I'll handle it. Just have waited till evening.

**Pull request merged**
