### PR TITLE
Announcement.

### PR DESCRIPTION
**Pull request by mrusme**

### CODE REVIEW

**Comment by Liongold** [comment]
I did not expect this announcement to be honest. Even though it is good news to see v2 take some form of shape, I have some questions about v1. What happens to v1? I've some non-pushed changes for that version. Should I open pull requests for them? Or is work on v1 stopped completely?

**Comment by mrusme** [comment]
@Liongold basically everyone is free to continue to contribute to whichever version they feel like. If you feel like continuing to build on the v1 base, I won't stop you from doing so. (besides, you should have admin rights on the repo anyway, don't you? :) ) However, if you want to jump on v2 and contribute there, I'd be happy to have you on-board!

**Comment by Liongold** [comment]
@mrusme I have some code which I think would be a pity wasting, that's why I asked about v1. So, do you think I should push changes to the 1 branch immediately or still use a pull request and let you merge it? 

I'd be interested in helping in v2 but I did not really understand where I can help for now. It seems like that is still at a concept stage.

**Comment by mrusme** [comment]
@Liongold feel free to push directly! Regarding v2, it really is a greenfield project still. However, I began building the first component, the user service, and wiring it to Kong. Maybe you want to check that one out and see whether you might want to jump in?

**Comment by Liongold** [comment]
@mrusme It seems like the `1` branch is protected and I'm not authorised to approve merges to that branch.

**Comment by mrusme** [comment]
@Liongold mind trying again? Should be ok now.

**Comment by Liongold** [comment]
@mrusme It's still saying the same thing.

**Pull request merged**
