### PR TITLE
Remove links in note after deleting attachment.

### LINKED ISSUE #141: delete attachment hyperlinks in note
upon deletion of any documents attached to a note, the hyperlinks pointing to the uploaded document remain in the document, they should be removed

### PR DESCRIPTION
**Pull request by ChrisLahaye**
Fixes #141

- Code add to remove hyperlinks to an attachment when an attachment is being deleted.
- Edit icon add to note template.

Will use different branches in the future since two unrelated commits are now in the same push request.
Let me know if you want DOM manipulation done by jQuery.

### CODE REVIEW

**Comment by Liongold** [comment]
@ChrisLahaye Do you think it would save a lot of code if done using jQuery?

**Comment by ChrisLahaye** [comment]
@Liongold 8 lines of code can be reduced to a one-liner but performance-wise direct DOM manipulation is a lot faster. so performance vs consistency

**Comment by Liongold** [comment]
I'll leave this for @devilx to decide since he is the lead here.

**Comment by devilx** [comment]
@ChrisLahaye looks good for me, although I'm more concerned about cross-browser compatibility, rather than code consistency. I couldn't spot anything within your JS code, that cause cross-browser issues here, but for more complex code we should stick to jQuery.
Thanks for this! :+1:

**Pull request merged**
