### PR TITLE
[WIP] alpine-nginx-php as base for Docker image

### PR DESCRIPTION
**Pull request by klud1**
Trying to make a lightweight image for paperwork using Nginx and PHP 5.x on Alpine

This is a Work in Progress

### CODE REVIEW

**Comment by Liongold** [comment]
Please change the base to develop. That is the branch where the latest code is hosted.

**Comment by klud1** [comment]
@Liongold my bad! Changed (^_^)

**Comment by Liongold** [comment]
@klud1 Any progress?

**Comment by klud1** [comment]
@Liongold sorry, been busy with college these days, will get back to work on this one by the weekend!

**Pull request merged**
