### PR TITLE
Fixed #109: Added Syntax Highlighting to code snippets

### LINKED ISSUE #109: Source code handling as note
Hi,

I use digital notebooks mostly for snippets / scripts / stuff I can hardly put into a file on my HDD. I need some kind of notebook which is capable of handling (displaying) source code correctly.

At the moment paperwork uses a non-fixed-width font. I'd like to see a solution so I can read source code in my browser.

Maybe using ACE as plugin or some other syntax highlighting would be cute.

### PR DESCRIPTION
**Pull request by Liongold**
I am using a timeout for this feature. Even though I understand this is not ideal, I wasn't able to find another way to run code when binding has finished.

### CODE REVIEW

**Comment by Baldrs** [comment]
You could use highlight js directive, then build content directive and use
$compile in it. That's the proper way

**Comment by Liongold** [comment]
@Baldrs Unfortunately, I wasn't able to find any information about how this can be implemented. All research I made has not resulted in anything that works. That means that unless I find something, it's difficult to implement this without using timeout. Do you think I should close this PM?

**Comment by Liongold** [comment]
Just a note, I am using a directive but it is not "waiting" until binding is complete.

**Comment by Baldrs** [comment]
I think yes, as interacting with the digest cycle and dom changes can be destructive if performed out of angular. You can update this PR by adding `pw-note-content` directive, which will preprocess given html and then will return modified one. I'll add a plunker later

**Comment by Baldrs** [comment]
Strange, I can't see any directive(s) defined or used in this pull request.

**Comment by Liongold** [comment]
Sorry I did not push it since it is not working. However, here's the directive code: 
```
    angular.module('paperworkNotes').directive('highlight', function($interpolate, $window){
        return {
        restrict: 'EA',
        scope: true,
        compile: function (tElem, tAttrs) {
          var interpolateFn = $interpolate(tElem.html(), true);
          tElem.html(''); // disable automatic intepolation bindings
          return function(scope, elem, attrs){
            console.log(elem);
            console.log(elem.find("pre"));
            scope.$watch(interpolateFn, function (value) {
              //elem.html(hljs.highlight('sql',value).value);
                console.log(elem);
            });
          }
        }
      };
    });
```
This is based on some snippets I have found around. The main problem is that both find() calls are not finding anything while there should be. What I intended to do was that I check for pre and then code, if true call the highlighting. Sorry again for not pushing to the repo earlier.

**Comment by Liongold** [comment]
All console.log() are working so directive is beign called, they're just not correct.

**Comment by Baldrs** [comment]
Found a way to do it properly. Will submit PR this evening.

**Comment by Liongold** [comment]
OK, thanks.

**Pull request closed without merging**
