### PR TITLE
Add composer dump-autoload instruction in README

### PR DESCRIPTION
**Pull request by wongalvis**

### CODE REVIEW

**Comment by Liongold** [comment]
Thank you for your contribution.

**Comment by Baldrs** [comment]
@Liongold  Why are you merging this into master while we all agreed that we don't merge everything into master?

**Comment by Baldrs** [comment]
@wongalvis why in first place you have deleted PR into develop?

**Comment by wongalvis** [comment]
Oops sorry I forgot to set the destination branch to the correct one.
@Baldrs Cause there involved a typo in the commit message and a line is somehow deleted at the end but I didn't have a local clone of the repo at that time so I dealt with it by deleting the branch and open a new one.

**Comment by wongalvis** [comment]
I would make a new PR into develop so that the one in master could be reverted. https://github.com/twostairs/paperwork/pull/309

**Pull request merged**
